# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_qtcalculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 600)
        MainWindow.setMaximumSize(QtCore.QSize(324, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(324, 600))
        self.centralwidget.setMaximumSize(QtCore.QSize(324, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_color = QtWidgets.QFrame(self.centralwidget)
        self.top_color.setMaximumSize(QtCore.QSize(16777215, 200))
        self.top_color.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(46, 191, 54, 255), stop:0.792135 rgba(255, 241, 68, 255));\n"
"border-radius: 10px;\n"
"")
        self.top_color.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_color.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_color.setObjectName("top_color")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.top_color)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.titlebar_frame = QtWidgets.QFrame(self.top_color)
        self.titlebar_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.titlebar_frame.setStyleSheet("background-color: none;")
        self.titlebar_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.titlebar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar_frame.setObjectName("titlebar_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.titlebar_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title = QtWidgets.QFrame(self.titlebar_frame)
        self.title.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.title.setFont(font)
        self.title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title.setObjectName("title")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.title)
        self.verticalLayout_3.setContentsMargins(15, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout.addWidget(self.title)
        self.titlebar_buttons = QtWidgets.QFrame(self.titlebar_frame)
        self.titlebar_buttons.setMaximumSize(QtCore.QSize(60, 16777215))
        self.titlebar_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titlebar_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titlebar_buttons.setObjectName("titlebar_buttons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.titlebar_buttons)
        self.horizontalLayout_2.setContentsMargins(-1, 5, 6, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_minimize = QtWidgets.QPushButton(self.titlebar_buttons)
        self.button_minimize.setMinimumSize(QtCore.QSize(13, 13))
        self.button_minimize.setMaximumSize(QtCore.QSize(13, 13))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.button_minimize.setFont(font)
        self.button_minimize.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: rgb(255, 170, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 170, 0, 150);\n"
"}")
        self.button_minimize.setText("")
        self.button_minimize.setObjectName("button_minimize")
        self.horizontalLayout_2.addWidget(self.button_minimize)
        self.button_close = QtWidgets.QPushButton(self.titlebar_buttons)
        self.button_close.setMinimumSize(QtCore.QSize(13, 13))
        self.button_close.setMaximumSize(QtCore.QSize(13, 13))
        self.button_close.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    background-color: rgb(255, 0, 0);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 0, 0, 150);\n"
"}")
        self.button_close.setText("")
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_2.addWidget(self.button_close)
        self.horizontalLayout.addWidget(self.titlebar_buttons)
        self.verticalLayout_4.addWidget(self.titlebar_frame)
        self.text_frame = QtWidgets.QFrame(self.top_color)
        self.text_frame.setStyleSheet("background-color: none;")
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.text_frame)
        self.verticalLayout_2.setContentsMargins(15, 3, 15, 30)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.text_frame)
        self.label.setMaximumSize(QtCore.QSize(16777215, 90))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("\n"
"QLabel {\n"
"  qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
"}\n"
"")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.result_field = QtWidgets.QLabel(self.text_frame)
        self.result_field.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.result_field.setFont(font)
        self.result_field.setStyleSheet("\n"
"QLabel {\n"
"  qproperty-alignment: \'AlignVCenter | AlignRight\';\n"
"}\n"
"")
        self.result_field.setText("")
        self.result_field.setObjectName("result_field")
        self.verticalLayout_2.addWidget(self.result_field)
        self.verticalLayout_4.addWidget(self.text_frame)
        self.verticalLayout.addWidget(self.top_color)
        self.keypad_frame = QtWidgets.QFrame(self.centralwidget)
        self.keypad_frame.setMaximumSize(QtCore.QSize(16777215, 405))
        self.keypad_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.keypad_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.keypad_frame.setObjectName("keypad_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.keypad_frame)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.button_9 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_9.setMinimumSize(QtCore.QSize(81, 81))
        self.button_9.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_9.setFont(font)
        self.button_9.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_9.setObjectName("button_9")
        self.gridLayout.addWidget(self.button_9, 3, 2, 1, 1)
        self.button_plus = QtWidgets.QPushButton(self.keypad_frame)
        self.button_plus.setMinimumSize(QtCore.QSize(81, 81))
        self.button_plus.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_plus.setFont(font)
        self.button_plus.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(223, 223, 223, 150);\n"
"}")
        self.button_plus.setObjectName("button_plus")
        self.gridLayout.addWidget(self.button_plus, 5, 3, 1, 1)
        self.button_5 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_5.setMinimumSize(QtCore.QSize(81, 81))
        self.button_5.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_5.setFont(font)
        self.button_5.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_5.setObjectName("button_5")
        self.gridLayout.addWidget(self.button_5, 4, 1, 1, 1)
        self.button_decimal = QtWidgets.QPushButton(self.keypad_frame)
        self.button_decimal.setMinimumSize(QtCore.QSize(81, 81))
        self.button_decimal.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_decimal.setFont(font)
        self.button_decimal.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_decimal.setObjectName("button_decimal")
        self.gridLayout.addWidget(self.button_decimal, 6, 2, 1, 1)
        self.button_7 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_7.setMinimumSize(QtCore.QSize(81, 81))
        self.button_7.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_7.setFont(font)
        self.button_7.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_7.setObjectName("button_7")
        self.gridLayout.addWidget(self.button_7, 3, 0, 1, 1)
        self.button_6 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_6.setMinimumSize(QtCore.QSize(81, 81))
        self.button_6.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_6.setFont(font)
        self.button_6.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_6.setObjectName("button_6")
        self.gridLayout.addWidget(self.button_6, 4, 2, 1, 1)
        self.button_equal = QtWidgets.QPushButton(self.keypad_frame)
        self.button_equal.setMinimumSize(QtCore.QSize(81, 81))
        self.button_equal.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_equal.setFont(font)
        self.button_equal.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(223, 223, 223, 150);\n"
"}")
        self.button_equal.setObjectName("button_equal")
        self.gridLayout.addWidget(self.button_equal, 6, 3, 1, 1)
        self.button_1 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_1.setMinimumSize(QtCore.QSize(81, 81))
        self.button_1.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_1.setFont(font)
        self.button_1.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_1.setObjectName("button_1")
        self.gridLayout.addWidget(self.button_1, 5, 0, 1, 1)
        self.button_8 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_8.setMinimumSize(QtCore.QSize(81, 81))
        self.button_8.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_8.setFont(font)
        self.button_8.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_8.setObjectName("button_8")
        self.gridLayout.addWidget(self.button_8, 3, 1, 1, 1)
        self.button_division = QtWidgets.QPushButton(self.keypad_frame)
        self.button_division.setMinimumSize(QtCore.QSize(81, 81))
        self.button_division.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_division.setFont(font)
        self.button_division.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(223, 223, 223, 150);\n"
"}")
        self.button_division.setObjectName("button_division")
        self.gridLayout.addWidget(self.button_division, 1, 3, 1, 1)
        self.button_4 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_4.setMinimumSize(QtCore.QSize(81, 81))
        self.button_4.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_4.setFont(font)
        self.button_4.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 4, 0, 1, 1)
        self.button_0 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_0.setMinimumSize(QtCore.QSize(162, 81))
        self.button_0.setMaximumSize(QtCore.QSize(162, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_0.setFont(font)
        self.button_0.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_0.setObjectName("button_0")
        self.gridLayout.addWidget(self.button_0, 6, 0, 1, 2)
        self.button_2 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_2.setMinimumSize(QtCore.QSize(81, 81))
        self.button_2.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_2.setFont(font)
        self.button_2.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_2.setObjectName("button_2")
        self.gridLayout.addWidget(self.button_2, 5, 1, 1, 1)
        self.button_multiplication = QtWidgets.QPushButton(self.keypad_frame)
        self.button_multiplication.setMinimumSize(QtCore.QSize(81, 81))
        self.button_multiplication.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_multiplication.setFont(font)
        self.button_multiplication.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(223, 223, 223, 150);\n"
"}")
        self.button_multiplication.setObjectName("button_multiplication")
        self.gridLayout.addWidget(self.button_multiplication, 3, 3, 1, 1)
        self.button_minus = QtWidgets.QPushButton(self.keypad_frame)
        self.button_minus.setMinimumSize(QtCore.QSize(81, 81))
        self.button_minus.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_minus.setFont(font)
        self.button_minus.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(223, 223, 223, 150);\n"
"}")
        self.button_minus.setObjectName("button_minus")
        self.gridLayout.addWidget(self.button_minus, 4, 3, 1, 1)
        self.button_percentage = QtWidgets.QPushButton(self.keypad_frame)
        self.button_percentage.setMinimumSize(QtCore.QSize(81, 81))
        self.button_percentage.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_percentage.setFont(font)
        self.button_percentage.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(223, 223, 223, 150);\n"
"}")
        self.button_percentage.setObjectName("button_percentage")
        self.gridLayout.addWidget(self.button_percentage, 1, 2, 1, 1)
        self.button_3 = QtWidgets.QPushButton(self.keypad_frame)
        self.button_3.setMinimumSize(QtCore.QSize(81, 81))
        self.button_3.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_3.setFont(font)
        self.button_3.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 150);\n"
"}")
        self.button_3.setObjectName("button_3")
        self.gridLayout.addWidget(self.button_3, 5, 2, 1, 1)
        self.button_pos_or_neg = QtWidgets.QPushButton(self.keypad_frame)
        self.button_pos_or_neg.setMinimumSize(QtCore.QSize(81, 81))
        self.button_pos_or_neg.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        self.button_pos_or_neg.setFont(font)
        self.button_pos_or_neg.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(223, 223, 223, 150);\n"
"}")
        self.button_pos_or_neg.setObjectName("button_pos_or_neg")
        self.gridLayout.addWidget(self.button_pos_or_neg, 1, 1, 1, 1)
        self.button_clear = QtWidgets.QPushButton(self.keypad_frame)
        self.button_clear.setMinimumSize(QtCore.QSize(81, 81))
        self.button_clear.setMaximumSize(QtCore.QSize(81, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.button_clear.setFont(font)
        self.button_clear.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 22px;\n"
"    background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgba(223, 223, 223, 150);\n"
"}")
        self.button_clear.setObjectName("button_clear")
        self.gridLayout.addWidget(self.button_clear, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.keypad_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.button_close.setToolTip(_translate("MainWindow", "Close"))
        self.label.setText(_translate("MainWindow", "0"))
        self.button_9.setText(_translate("MainWindow", "9"))
        self.button_plus.setText(_translate("MainWindow", "+"))
        self.button_5.setText(_translate("MainWindow", "5"))
        self.button_decimal.setText(_translate("MainWindow", "."))
        self.button_7.setText(_translate("MainWindow", "7"))
        self.button_6.setText(_translate("MainWindow", "6"))
        self.button_equal.setText(_translate("MainWindow", "="))
        self.button_1.setText(_translate("MainWindow", "1"))
        self.button_8.setText(_translate("MainWindow", "8"))
        self.button_division.setText(_translate("MainWindow", "/"))
        self.button_4.setText(_translate("MainWindow", "4"))
        self.button_0.setText(_translate("MainWindow", "0"))
        self.button_2.setText(_translate("MainWindow", "2"))
        self.button_multiplication.setText(_translate("MainWindow", "x"))
        self.button_minus.setText(_translate("MainWindow", "-"))
        self.button_percentage.setText(_translate("MainWindow", "%"))
        self.button_3.setText(_translate("MainWindow", "3"))
        self.button_pos_or_neg.setText(_translate("MainWindow", "+/-"))
        self.button_clear.setText(_translate("MainWindow", "AC"))

        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
